# Use official Node.js image as base
FROM node:latest AS build

# Set working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application
COPY . .

# Build the Angular application
RUN npm run build --prod

# Use a lightweight web server to serve the Angular app
FROM nginx:latest

WORKDIR /usr/share/nginx/html

RUN rm -rf ./*

# Copy the built Angular app to the Nginx server's public directory
COPY --from=build /app/dist/demo/browser .

# Expose port 80
EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]
