# Use official Node.js image as base
FROM node:20-alpine AS build

# Set working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application
COPY . .

# Build the Angular application
RUN npm run build -- --prod

# Use a lightweight web server to serve the Angular app
FROM nginx:alpine

# Copy the built Angular app to the Nginx server's public directory
COPY --from=build /app/dist/demo /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]
