services:
  backend:
    build:
      context: ./backend
    container_name: fastapi_backend
    ports:
      - "8000:8000" 
    depends_on:
      - postgres 

  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: fastapi
    ports:
      - "5433:5432" 

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80" 
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend  
    container_name: angular_frontend
    ports:
      - "80:80"  
    depends_on:
      - backend 
